### ISSUE TITLE
Error:Could not find com.github.mychoices:Jgraph:v1.2.

### ISSUE THREAD

**Issue by sashatinkoff** [mychoices/Jgraph#4]
Error:Could not find com.github.mychoices:Jgraph:v1.2.
Required by:
    app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by YESO12138** [comment]
I have also this program.Who can tell me why?

**Comment by annie-l** [comment]
hi, is the [gradle information in the readme](https://github.com/ZuYun/Jgraph/blob/master/README.md#gradle) still accurate?


```
allprojects {
        repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
dependencies {
    compile 'com.github.mychoices:Jgraph:v1.2'
}
```

it seems like the maven line should be in the top-level project's build.gradle and the compile line should be in the app module's build.gradle. but i get this error when trying to sync gradle:

```
Error:(60, 13) Failed to resolve: com.github.mychoices:Jgraph:v1.2
```
also:
```
Error:(60, 13) Failed to resolve: com.github.mychoices:Jgraph:16.07.30
```

looks like you have a newer version than 1.2 now, and i'm confused about the package name since your username is `ZuYun`, not `mychoices`, and in your code i'm seeing the package name `com.jonas.schart`.

it's a beautiful charting library that i'd love to use if i could get it to compile.

**Comment by 5hmlA** [comment]
You can download the source code to understand the idea of ​​animation, it is recommended not to use directly in your project ，thanks
